-- Для @GeneratedValue(strategy = GenerationType.IDENTITY)
/*
create table client
(
    id   bigserial not null primary key,
    name varchar(50)
);

 */

-- Для @GeneratedValue(strategy = GenerationType.SEQUENCE)
create sequence hibernate_sequence start with 1 increment by 1;

create table client
(
    id   bigint not null primary key,
    name varchar(50),
    address_id bigint
);

create table address
(
    id   bigint not null primary key generated by default as identity,
    street varchar(50)
);

alter table client
    add constraint address_fk
        foreign key (address_id)
            references address;

create table phone
(
    id   bigint not null primary key generated by default as identity,
    number varchar(50),
    client_id bigint
);

alter table phone
    add constraint phone_fk
        foreign key (client_id)
            references client;